Planejamento projeto
Requisitos-de-Software/2022.2-LinkedIn pull request #1
Opened 2022-11-10 13:07 UTC by Mateusvff

2022-11-17 01:10 UTC, guibrbs requested changes

2022-11-17 01:10 UTC, guibrbs commented on docs/planejamento/metodologias.md
> +* ⬇️ quando realizar downgrade de dependências `:arrow_down:`
Acredito que na Política de Commit não necessitamos de ter separação entre front-end, back-end e nem questões como melhorar o desempenho, adicionar testes, lidar com segurança etc, já que nosso escopo é somente documentação.

2022-11-17 01:13 UTC, guibrbs commented on mkdocs.yml
> +    - Rich Picture: ./preRastreabilidade/rich-picture.md
Acredito que vai ser preciso remover isso, já que o Rich Picture está sendo abordado em outra branch

2022-11-18 12:33 UTC, LeticiaAires approved these changes

2022-11-18 12:39 UTC, merged